In [1]:
from mingptf.model import GPT
import numpy as np

2023-01-09 14:36:05.187789: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
model_config = GPT.get_default_config()
model_config.model_type = 'gpt-nano'


model_config.vocab_size = 28512
model_config.block_size = 128
model = GPT(model_config)

2023-01-09 14:36:12.398452: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
model_config.n_embd

48

In [4]:
model(np.array([[1,2]]))

tf.Tensor(
[[[[0. 1.]
   [0. 0.]]]], shape=(1, 1, 2, 2), dtype=float32)


<tf.Tensor: shape=(1, 2, 28512), dtype=float32, numpy=
array([[[-0.0012789 ,  0.12221976, -0.10653678, ...,  0.05964127,
          0.04251818, -0.0428572 ],
        [-0.02710285,  0.10838187, -0.06904468, ...,  0.05702014,
          0.05607553, -0.02463269]]], dtype=float32)>