In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from mingptf.model import GPT
import numpy as np

In [4]:
model_config = GPT.get_default_config()
model_config.model_type = 'gpt2'


model_config.vocab_size = 50000
model_config.block_size = 1024
model = GPT(model_config)

tf.Tensor(
[[[[0. 1. 1.]
   [0. 0. 1.]
   [0. 0. 0.]]]], shape=(1, 1, 3, 3), dtype=float32)
number of parameters: 124.24M


In [5]:
model_config.n_embd

768

In [6]:
model(np.array([[1,2]]))

tf.Tensor(
[[[[0. 1.]
   [0. 0.]]]], shape=(1, 1, 2, 2), dtype=float32)


<tf.Tensor: shape=(1, 2, 50000), dtype=float32, numpy=
array([[[ 0.55168974, -1.3506098 ,  0.05488223, ..., -0.05919582,
         -0.28045064,  0.252296  ],
        [ 0.6015008 , -1.6132736 ,  0.3849807 , ...,  0.2904365 ,
         -0.7388692 ,  0.25072742]]], dtype=float32)>

In [13]:
a = [b.name for b in model.weights]

In [ ]:
model = GPT.from_pretrained('gpt2')

In [15]:
from transformers import TFGPT2LMHeadModel

/Users/abhaykumar/opt/anaconda3/envs/mingpt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [16]:
model_hf = TFGPT2LMHeadModel.from_pretrained('gpt2')

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [17]:
b = [c.name for c in model_hf.weights]

In [18]:
a

['wte/embeddings:0',
 'wpe/embeddings:0',
 'layer_normalization_175/gamma:0',
 'layer_normalization_175/beta:0',
 'dense_336/kernel:0',
 'dense_336/bias:0',
 'dense_337/kernel:0',
 'dense_337/bias:0',
 'layer_normalization_176/gamma:0',
 'layer_normalization_176/beta:0',
 'dense_338/kernel:0',
 'dense_338/bias:0',
 'dense_339/kernel:0',
 'dense_339/bias:0',
 'layer_normalization_177/gamma:0',
 'layer_normalization_177/beta:0',
 'dense_340/kernel:0',
 'dense_340/bias:0',
 'dense_341/kernel:0',
 'dense_341/bias:0',
 'layer_normalization_178/gamma:0',
 'layer_normalization_178/beta:0',
 'dense_342/kernel:0',
 'dense_342/bias:0',
 'dense_343/kernel:0',
 'dense_343/bias:0',
 'layer_normalization_179/gamma:0',
 'layer_normalization_179/beta:0',
 'dense_344/kernel:0',
 'dense_344/bias:0',
 'dense_345/kernel:0',
 'dense_345/bias:0',
 'layer_normalization_180/gamma:0',
 'layer_normalization_180/beta:0',
 'dense_346/kernel:0',
 'dense_346/bias:0',
 'dense_347/kernel:0',
 'dense_347/bias:0',
 'la

In [19]:
b

['tfgpt2lm_head_model/transformer/wpe/embeddings:0',
 'tfgpt2lm_head_model/transformer/wte/weight:0',
 'tfgpt2lm_head_model/transformer/h_._0/ln_1/gamma:0',
 'tfgpt2lm_head_model/transformer/h_._0/ln_1/beta:0',
 'tfgpt2lm_head_model/transformer/h_._0/attn/c_attn/weight:0',
 'tfgpt2lm_head_model/transformer/h_._0/attn/c_attn/bias:0',
 'tfgpt2lm_head_model/transformer/h_._0/attn/c_proj/weight:0',
 'tfgpt2lm_head_model/transformer/h_._0/attn/c_proj/bias:0',
 'tfgpt2lm_head_model/transformer/h_._0/ln_2/gamma:0',
 'tfgpt2lm_head_model/transformer/h_._0/ln_2/beta:0',
 'tfgpt2lm_head_model/transformer/h_._0/mlp/c_fc/weight:0',
 'tfgpt2lm_head_model/transformer/h_._0/mlp/c_fc/bias:0',
 'tfgpt2lm_head_model/transformer/h_._0/mlp/c_proj/weight:0',
 'tfgpt2lm_head_model/transformer/h_._0/mlp/c_proj/bias:0',
 'tfgpt2lm_head_model/transformer/h_._1/ln_1/gamma:0',
 'tfgpt2lm_head_model/transformer/h_._1/ln_1/beta:0',
 'tfgpt2lm_head_model/transformer/h_._1/attn/c_attn/weight:0',
 'tfgpt2lm_head_mode

In [20]:
len(a), len(b)

(148, 148)

In [29]:
for s in model.weights:
    print(s.name)
    break

wte/embeddings:0


In [27]:
model.trainable_weights

[<tf.Variable 'wte/embeddings:0' shape=(50000, 768) dtype=float32, numpy=
 array([[-0.00582082, -0.0477948 , -0.0459661 , ...,  0.015922  ,
         -0.02913424, -0.01246445],
        [-0.01916666,  0.04260984,  0.04796895, ...,  0.00545939,
          0.04250467,  0.03213023],
        [ 0.00471765, -0.02981058, -0.02236938, ..., -0.04674648,
         -0.04266567, -0.02022871],
        ...,
        [ 0.018828  , -0.04553313,  0.04092875, ...,  0.03819614,
          0.02460588, -0.04621159],
        [ 0.02395025,  0.02207131,  0.00233897, ...,  0.0199777 ,
         -0.04606556,  0.04199285],
        [ 0.04521811,  0.00573165, -0.04135894, ..., -0.00073054,
         -0.01486343,  0.03134483]], dtype=float32)>,
 <tf.Variable 'wpe/embeddings:0' shape=(1024, 768) dtype=float32, numpy=
 array([[ 0.00502821,  0.01091479, -0.00415901, ..., -0.03241968,
         -0.0248969 ,  0.01975727],
        [-0.03448967, -0.04213353, -0.03569324, ...,  0.04203561,
          0.00991011,  0.02180017],
      

In [28]:
def get_weights_by_name(model, name):
    return [w for w in model.weights if w.name == name][0]

In [31]:
get_weights_by_name(model, "wte/embeddings:0").shape

TensorShape([50000, 768])