In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from mingptf.model import GPT
import numpy as np
import tensorflow as tf

2023-01-09 20:34:15.301313: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
model_config = GPT.get_default_config()
model_config.model_type = 'gpt2'


model_config.vocab_size = 50257
model_config.block_size = 1024
model = GPT(model_config)

2023-01-09 20:34:22.971208: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


number of parameters: 124.44M


In [4]:
model_config.n_embd

768

In [5]:
model(np.array([[1,2], [3, 7]]))

tf.Tensor(
[[[[0. 1.]
   [0. 0.]]]


 [[[0. 1.]
   [0. 0.]]]], shape=(2, 1, 2, 2), dtype=float32)


<tf.Tensor: shape=(2, 2, 50257), dtype=float32, numpy=
array([[[-1.8195261 , -0.76071787,  0.8499795 , ..., -1.2292076 ,
          0.758211  ,  1.2788966 ],
        [-1.6374478 , -1.1465895 ,  1.3667431 , ..., -1.2096674 ,
         -0.00726241,  0.5388917 ]],

       [[-0.442382  , -1.3302209 ,  0.48249912, ..., -1.2787623 ,
         -1.1074531 , -0.28627527],
        [-0.3812474 , -0.78727275,  0.9636992 , ..., -1.1547761 ,
         -1.3862071 , -0.06851846]]], dtype=float32)>

In [6]:
a = [b.name for b in model.weights]

In [4]:
model = GPT.from_pretrained('gpt2')

/Users/abhaykumar/opt/anaconda3/envs/mingpt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


number of parameters: 124.44M


All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


tfgpt2lm_head_model/transformer/wpe/embeddings:0 ---- gpt_1/wpe/embeddings:0
tfgpt2lm_head_model/transformer/wte/weight:0 ---- gpt_1/wte/embeddings:0
tfgpt2lm_head_model/transformer/h_._0/ln_1/gamma:0 ---- gpt_1/block_12/ln_1/gamma:0
tfgpt2lm_head_model/transformer/h_._0/ln_1/beta:0 ---- gpt_1/block_12/ln_1/beta:0
tfgpt2lm_head_model/transformer/h_._0/attn/c_attn/weight:0 ---- gpt_1/block_12/causal_self_attention_12/c_attn/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._0/attn/c_proj/weight:0 ---- gpt_1/block_12/causal_self_attention_12/c_proj/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._0/ln_2/gamma:0 ---- gpt_1/block_12/ln_2/gamma:0
tfgpt2lm_head_model/transformer/h_._0/ln_2/beta:0 ---- gpt_1/block_12/ln_2/beta:0
tfgpt2lm_head_model/transformer/h_._0/mlp/c_fc/weight:0 ---- gpt_1/block_12/mlp_12/c_fc/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._0/mlp/c_proj/weight:0 ---- gpt_1/block_12/mlp_12/c_proj/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._1/ln_1/gamma:0 ---- gpt_1/bl

0.0
tfgpt2lm_head_model/transformer/h_._10/attn/c_proj/weight:0 ---- gpt_1/block_22/causal_self_attention_22/c_proj/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._10/ln_2/gamma:0 ---- gpt_1/block_22/ln_2/gamma:0
tfgpt2lm_head_model/transformer/h_._10/ln_2/beta:0 ---- gpt_1/block_22/ln_2/beta:0
tfgpt2lm_head_model/transformer/h_._10/mlp/c_fc/weight:0 ---- gpt_1/block_22/mlp_22/c_fc/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._10/mlp/c_proj/weight:0 ---- gpt_1/block_22/mlp_22/c_proj/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._11/ln_1/gamma:0 ---- gpt_1/block_23/ln_1/gamma:0
tfgpt2lm_head_model/transformer/h_._11/ln_1/beta:0 ---- gpt_1/block_23/ln_1/beta:0
tfgpt2lm_head_model/transformer/h_._11/attn/c_attn/weight:0 ---- gpt_1/block_23/causal_self_attention_23/c_attn/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._11/attn/c_proj/weight:0 ---- gpt_1/block_23/causal_self_attention_23/c_proj/kernel:0
0.0
tfgpt2lm_head_model/transformer/h_._11/ln_2/gamma:0 ---- gpt_1/block_23/ln_2/

In [5]:
from transformers import TFGPT2LMHeadModel

In [6]:
model_hf = TFGPT2LMHeadModel.from_pretrained('gpt2')

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [7]:
model(np.array([[1,2]]))

<tf.Tensor: shape=(1, 2, 50257), dtype=float32, numpy=
array([[[-32.93364 , -31.234602, -34.697796, ..., -39.52408 ,
         -39.911842, -32.270668],
        [-55.62229 , -53.536892, -56.584724, ..., -68.26166 ,
         -66.886566, -58.69557 ]]], dtype=float32)>

In [8]:
b = model_hf(np.array([[1,2]]))

In [10]:
b[0]

<tf.Tensor: shape=(1, 2, 50257), dtype=float32, numpy=
array([[[-32.901066, -31.202394, -34.662235, ..., -39.48672 ,
         -39.873142, -32.23869 ],
        [-55.52077 , -53.428535, -56.476707, ..., -68.15389 ,
         -66.77085 , -58.600616]]], dtype=float32)>

In [ ]:
for s in model.weights:
    print(s.name)
    break

In [56]:
def get_weights_by_name(model, name):
    return [w for w in model.weights if w.name == name][0]

In [57]:
get_weights_by_name(model, "wte/embeddings:0").shape

IndexError: list index out of range

In [28]:
p = "/Users/abhaykumar/.cache/huggingface/hub/models--gpt2/blobs/d08c1307f7dfae6f878e0a2ca5715d587d2640530db8ef96fc0c1fc474dd9fee"
#model.load_weights(p)

In [8]:
model.set_weights(model_hf.get_weights()) 

ValueError: Layer gpt weight shape (2304,) is not compatible with provided weight shape (1, 2304).

In [11]:
model_hf.trainable_variables

[<tf.Variable 'tfgpt2lm_head_model/transformer/wpe/embeddings:0' shape=(1024, 768) dtype=float32, numpy=
 array([[-1.8820720e-02, -1.9741860e-01,  4.0267250e-03, ...,
         -4.3043736e-02,  2.8267192e-02,  5.4490108e-02],
        [ 2.3959434e-02, -5.3792033e-02, -9.4878644e-02, ...,
          3.4170013e-02,  1.0171850e-02, -1.5572949e-04],
        [ 4.2160717e-03, -8.4763914e-02,  5.4514930e-02, ...,
          1.9744711e-02,  1.9324856e-02, -2.1423856e-02],
        ...,
        [-1.7986511e-03,  1.6052092e-03, -5.5103153e-02, ...,
          1.3616630e-02, -7.1805264e-03,  3.7552188e-03],
        [ 3.2105497e-03,  1.5500595e-03, -4.8944373e-02, ...,
          2.0725457e-02, -1.1837787e-02, -5.5682898e-04],
        [ 2.6609693e-04,  3.0272407e-03, -1.7086461e-03, ...,
         -4.6505518e-03, -2.3541194e-03, -5.7855090e-03]], dtype=float32)>,
 <tf.Variable 'tfgpt2lm_head_model/transformer/wte/weight:0' shape=(50257, 768) dtype=float32, numpy=
 array([[-0.11010301, -0.03926672,  0.0331

In [12]:
model.trainable_variables

[<tf.Variable 'gpt/wpe/embeddings:0' shape=(1024, 768) dtype=float32, numpy=
 array([[ 0.0027055 , -0.02526573, -0.02778301, ...,  0.02502109,
         -0.00606298,  0.00964625],
        [ 0.00364728,  0.00627916,  0.04496007, ..., -0.02635831,
         -0.01322827, -0.02262964],
        [ 0.04703047,  0.02478563,  0.0382886 , ..., -0.04016344,
         -0.00761615,  0.04523423],
        ...,
        [-0.03163917,  0.00701027, -0.03126469, ..., -0.04334998,
         -0.02887278,  0.0274166 ],
        [-0.00711098, -0.02735202,  0.00025587, ..., -0.01939313,
         -0.04656509,  0.04552144],
        [ 0.0235075 , -0.02544074,  0.04763067, ..., -0.00393788,
          0.01854818,  0.03902486]], dtype=float32)>,
 <tf.Variable 'gpt/wte/embeddings:0' shape=(50257, 768) dtype=float32, numpy=
 array([[ 0.00241876, -0.02443737, -0.03839967, ..., -0.0083758 ,
          0.04934552,  0.02290428],
        [-0.02922957, -0.00069349,  0.01095085, ...,  0.03633267,
          0.04493398, -0.00236094]

In [53]:
for i in model_hf.trainable_variables:
    if "bias" in i.name:
        print(i.numpy)
        break

<bound method BaseResourceVariable.numpy of <tf.Variable 'tfgpt2lm_head_model_1/transformer/h_._0/attn/c_attn/bias:0' shape=(1, 2304) dtype=float32, numpy=
array([[ 0.48033914, -0.5254326 , -0.42926455, ...,  0.01257301,
        -0.04987717,  0.00324764]], dtype=float32)>>


In [67]:
for i, weights in enumerate(model_hf.trainable_variables):
    print(i)
    #model.layers[i].set_weights(weights)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147


In [68]:
for i, weights in enumerate(model.trainable_variables):
    print(i)
    #model.layers[i].set_weights(weights)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147


In [87]:
a = np.random.rand(768, 2304)

In [88]:
a

array([[0.6784941 , 0.9984481 , 0.42002711, ..., 0.38509512, 0.02796772,
        0.84635355],
       [0.04278161, 0.16783717, 0.25816526, ..., 0.09318697, 0.73350738,
        0.6223124 ],
       [0.15174349, 0.73569792, 0.06701407, ..., 0.49966842, 0.82171986,
        0.08920879],
       ...,
       [0.4215996 , 0.7781665 , 0.11050358, ..., 0.28725985, 0.38746069,
        0.98755134],
       [0.94932639, 0.3667856 , 0.22943362, ..., 0.76622839, 0.37887708,
        0.34263844],
       [0.62401787, 0.71212149, 0.35693048, ..., 0.36094192, 0.6958837 ,
        0.57984809]])

In [90]:
model.trainable_variables[4]#.assign(a)

<tf.Variable 'gpt/block/causal_self_attention/c_attn/kernel:0' shape=(768, 2304) dtype=float32, numpy=
array([[0.6784941 , 0.9984481 , 0.4200271 , ..., 0.38509512, 0.02796772,
        0.84635353],
       [0.04278161, 0.16783717, 0.25816527, ..., 0.09318697, 0.7335074 ,
        0.62231237],
       [0.1517435 , 0.7356979 , 0.06701407, ..., 0.49966842, 0.8217199 ,
        0.08920879],
       ...,
       [0.4215996 , 0.7781665 , 0.11050358, ..., 0.28725985, 0.38746068,
        0.98755133],
       [0.9493264 , 0.36678562, 0.22943361, ..., 0.7662284 , 0.37887707,
        0.34263843],
       [0.6240179 , 0.7121215 , 0.35693046, ..., 0.36094192, 0.6958837 ,
        0.5798481 ]], dtype=float32)>